name: CD — Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # [] ko hata kar humne 'test' likha taaki pehle CI file run ho
    needs: [test]   

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1
        with:
          host:     ${{ secrets.EC2_HOST }}
          username: ubuntu
          key:      ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/devops-project
            git pull origin main
            # Agar aapke server par .env.production file nahi bani hai, 
            # toh yeh line fail ho sakti hai. Isliye 'touch' use kar rhe hain safe side ke liye.
            touch .env.production
            cp .env.production .env
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d --build
            echo "Deployed at $(date)"