name: CD — Deploy to EC2

on:
  workflow_run:
    workflows: ["CI — Lint and Test"] 
    types:
      - completed                     

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Yeh condition check karegi ki CD tabhi chale jab CI successfully PASS (completed) hui ho
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1
        with:
          host:     ${{ secrets.EC2_HOST }}
          username: ubuntu
          key:      ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/devops-project
            git pull origin main
            touch .env.production
            cp .env.production .env
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d --build
            echo "Deployed at $(date)"